export const PATHWAYS = [
  'DYNAMIC_LEADERSHIP', 'EFFECTIVE_COACHING', 'INNOVATIVE_PLANNING',
  'LEADERSHIP_DEVELOPMENT', 'MOTIVATIONAL_STRATEGIES', 'PERSUASIVE_INFLUENCE',
  'PRESENTATION_MASTERY', 'STRATEGIC_RELATIONSHIPS', 'TEAM_COLLABORATION',
  'VISIONARY_COMMUNICATION', 'ENGAGING_HUMOR'
];
