name: Infra - Hard Reset VM
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "RESET" to confirm hard reset'
        required: true


jobs:
  hard-reset:
    runs-on: self-hosted
    steps:
      - name: Purge Docker Environment
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ "${{ github.event.inputs.confirm }}" != "RESET" ]; then
              echo "Abort: Confirmation mismatch."
              exit 1
            fi
            echo ">>> PERFORMEING SYSTEM WIPE..."
            docker stop $(docker ps -aq) || true
            docker rm -f $(docker ps -aq) || true
            docker network prune -f
            docker volume prune -af
            docker image prune -af
            docker system prune -af --volumes
            echo ">>> SYSTEM PURGED. STORAGE RECLAIMED."
